# Notebook to plot correlation between technical replicates for each condition

## Import libraries

In [1]:
import pandas as pd
import re
import itertools
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['svg.fonttype'] = 'none'

## Specify paths

In [2]:
aggdata_outpath = '../aggregated_data/'
diagnostics_graph_outpath = '../diagnostics_graphs/'

## Reshaping

In [3]:
master = pd.read_csv(f'{aggdata_outpath}/master.csv', index_col=0)
p = re.compile(r'selcoeff_[1-3]')
replicates = [x for x in master.columns if bool(p.fullmatch(x))]
replicates

['selcoeff_1', 'selcoeff_2', 'selcoeff_3']

In [4]:
rep_combinations = list(itertools.combinations(replicates, 2))
rep_combinations

[('selcoeff_1', 'selcoeff_2'),
 ('selcoeff_1', 'selcoeff_3'),
 ('selcoeff_2', 'selcoeff_3')]

In [5]:
NT = master[(master.pool_type == 'single') & (master.compound != 'none') 
           ].groupby(['strain','locus','pool_type','compound','nt_seq','confidence_score']
                    )[replicates].first().reset_index()
NT

,strain,locus,pool_type,compound,nt_seq,confidence_score,selcoeff_1,selcoeff_2,selcoeff_3
0,BY4741,FKS1-HS1,single,anidulafungin,aagttagttttatctttgagagatcca,1.0,1.453951,1.392818,NaN
1,BY4741,FKS1-HS1,single,anidulafungin,aatttagttttatctttgagagatcca,1.0,0.998118,0.861958,NaN
2,BY4741,FKS1-HS1,single,anidulafungin,acgttagttttatctttgagagatcca,1.0,1.124241,1.022551,NaN
3,BY4741,FKS1-HS1,single,anidulafungin,actttagttttatctttgagagatcca,1.0,1.474356,1.390547,NaN
4,BY4741,FKS1-HS1,single,anidulafungin,aggttagttttatctttgagagatcca,1.0,1.610172,1.385900,NaN
...,...,...,...,...,...,...,...,...,...
6629,R1158,FKS2-HS2,single,micafungin,tcttggttgaaaagatgtgttatt,1.0,0.157966,0.036769,-0.161181
6630,R1158,FKS2-HS2,single,micafungin,tggtgggtgagacgttatacactc,1.0,-0.158556,-0.419717,0.232059
6631,R1158,FKS2-HS2,single,micafungin,ttgtggattaaaagaactattatt,1.0,-0.286497,-0.085537,-0.137888
6632,R1158,FKS2-HS2,single,micafungin,ttgtgggtgagacgttatacactc,1.0,-0.186787,-0.175503,-0.081081
6633,R1158,FKS2-HS2,single,micafungin,ttttgggtgagacgttatacactc,1.0,-0.231064,-0.191039,-0.110698

In [6]:
gby = NT.groupby(['strain','locus','compound'])[replicates].nunique()
gby

                               selcoeff_1  selcoeff_2  selcoeff_3
strain locus    compound
BY4741 FKS1-HS1 anidulafungin         306         306           0
                caspofungin           306         302           0
                micafungin            310         303           0
       FKS1-HS2 anidulafungin         212         211         207
                caspofungin           207         204         204
                micafungin            209         202         204
       FKS1-HS3 anidulafungin         326         319           0
                caspofungin           317         314           0
                micafungin            314         323           0
R1158  FKS1-HS1 anidulafungin         242         257         253
                caspofungin           240         247         240
                dox                   244         247         250
                micafungin            243         245         239
       FKS1-HS2 anidulafungin         199         200         154
                caspofungin           198         199         162
                dox                   199         200         195
                micafungin            199         197         152
       FKS2-HS1 anidulafungin         228         230         230
                caspofungin           229         231         232
                dox                   232         238         229
                micafungin            233         231         232
       FKS2-HS2 anidulafungin           0         233         229
                caspofungin           230         227         229
                dox                   233         239         230
                micafungin            227         228         231

In [7]:
def rep_pairwise(df,s,l,c,rc):
    sns.set(rc = {
              'font.family':'Arial',
              'font.size':8,
              'legend.title_fontsize':8, 'legend.fontsize':8,
              'axes.labelsize':8,'axes.titlesize':8,
              'xtick.labelsize':8, 'ytick.labelsize':8,
              'xtick.major.pad':2, 'ytick.major.pad':2,
              'xtick.bottom': True, 'ytick.left': True,
              'xtick.major.size':2, 'ytick.major.size':2,
             },
       style='ticks')
    
    graphdf = df[(df.strain == s)
                 & (df.locus == l)
                 & (df.compound == c)
                ]
    
    # Get Pearson correlation coefficient
    from scipy import stats

    pearson_dict = {}
    for x in rc:
        if (graphdf[x[0]].nunique() > 0) & (graphdf[x[1]].nunique() > 0):
            pearson_dict[x] = stats.pearsonr(graphdf[x[0]], graphdf[x[1]])[0]
    
    # Draw plot
    graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
                            'selcoeff_2':'s (Rep. 2)',
                            'selcoeff_3':'s (Rep. 3)'
                           }, inplace=True)
    
    fig = sns.pairplot(graphdf, diag_kind=None, corner=True,
                       hue='confidence_score', hue_order=[1,2,3], palette=['green','orange','red'],
                       plot_kws={'alpha':.2},
                       height=1)
    
    # axes[i][j] corresponds to (replicate j+1, replicate i+1)
    # (replicate x, replicate y) corresponds to axes[y-1][x-1]
    for k,v in pearson_dict.items():
        fig.axes[int(k[1][-1]) - 1
                ][int(k[0][-1]) -1
                 ].annotate(f'{v:.2}',(0,0), ha='center', va='center',
                            bbox=dict(facecolor='white', alpha=.8,
                                      edgecolor='black', boxstyle='round,pad=.5')
                           )
    plt.annotate(f'{s}\n{l}\n{c.title()}', (.75,.5), xycoords='figure fraction')
    
    plt.savefig(f'{diagnostics_graph_outpath}/{s}_{l}_{c}_Pearson.svg', format='svg', dpi=300)
    plt.close()
    return

In [8]:
for g in gby.index:
    rep_pairwise(NT, g[0], g[1], g[2], rep_combinations)

/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',
/tmp/ipykernel_1334/706942091.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  graphdf.rename(columns={'selcoeff_1':'s (Rep. 1)',